satsigner/satsigner

CONTRIBUTING.md

Just to understand a starting point for anyone that stumbles along.

Add brief CONTRIBUTING.md file for new comers to the project.

---

.gitignore
README.md

Added Dev Environment Setup section to the readme with directions for getting React Native setup and steps for both Android and iOS

Readme dev setup update

---

android/app/src/main/AndroidManifest.xml
package.json
src/components/accounts/AccountsContext.ts
src/components/accounts/AccountsProvider.tsx
src/components/accounts/ImportSeedScreen.tsx
src/components/accounts/SeedWordInfo.ts
src/components/accounts/Word.tsx
src/components/accounts/WordSelector.tsx
src/components/shared/getWordList.ts
src/components/shared/usePrevious.ts
src/styles/colors.ts
yarn.lock

When two characters of a seed word are entered, a word selector control displaying matching words from the bip39 word list fades in above the keyboard.  KeyboardAwareScrollView is used to make sure word listing does not cover the text input.  When a word is selected from the list, it is entered into the seed word text input and the word selector disappears.
Also includes use of passphrase entered by user when importing mnemonic.

Implements word selector control populated with bip39 word list

---

src/App.tsx
src/components/HomeScreen.tsx
src/types/navigation.d.ts

- Navigation Screen Types added with undefined params
- useNavigation hook used for navigation in HomeScreen
- RootStackParams types added in App.tsx (useStackNavigator hook)

[TYPES] Native Stack Navigation Screen Types

---

apps/mobile/app/accountList/account/[id]/signAndSend/selectUtxoBubbles.tsx
apps/mobile/components/SSUtxoBubble.tsx

This PR consist of the following fixes:
- Android text rendering issue in Skia using custom font: SF Pro Text
- Styling the text inside bubbles.
- Linear gradient for the submit container.

UTXO Bubbles Text Rendering in Android

---

apps/mobile/app/(authenticated)/account/[id]/signAndSend/selectUtxoBubbles.tsx
apps/mobile/components/SSUtxoBubble.tsx

use react native api instead of react native gesture handler for performance improvement, caveat: there will be flickering

Single Tapping Bubbles Performance

---

apps/mobile/app/(authenticated)/account/[id]/signAndSend/feeSelection.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/ioPreview.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/messageConfirmation.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/previewMessage.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/selectUtxoBubbles.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/selectUtxoList.tsx
apps/mobile/app/(authenticated)/account/[id]/signAndSend/signMessage.tsx
apps/mobile/components/SSButton.tsx
apps/mobile/components/SSModal.tsx
apps/mobile/components/SSPinInput.tsx
apps/mobile/components/SSTextInput.tsx
apps/mobile/components/icons/ScanIcon.tsx
apps/mobile/eas.json
apps/mobile/locales/en.json
apps/mobile/store/transactionBuilder.ts
apps/mobile/styles/sizes.ts
apps/mobile/types/models/Output.ts
apps/mobile/utils/id.ts

IO Preview (without bowtie chart)
Add output view paste & camera
Add memo
Set message fee (without fee chart)
Preview Message
Sign Message
Broadcast Message

DRAFT: Transactions Progress

---

apps/mobile/app/(authenticated)/account/[id]/camera.tsx
apps/mobile/tests/unit/utils/bitcoin.test.ts
apps/mobile/utils/bitcoin.ts
apps/mobile/utils/clipboard.ts
apps/mobile/utils/format.ts

- move clipbaord functionality to own file
- only paste if bitcoin address for now

fix bug paste

---

apps/mobile/api/bdk.ts
apps/mobile/app/(authenticated)/account/[id]/newInvoice.tsx
apps/mobile/hooks/useGetWalletAddress.ts

Credits to @phuncti0n 
- Create new invoice using `account.summary.numberOfAddresses` as the last used
- Showing number, path, qrcode and address string in `newInvoice` page
> [Trello Task](https://trello.com/c/c1LILvas/49-new-invoice-a-zach)

New Invoice

---

apps/mobile/components/SSTransactionCard.tsx

Got this when trying to run locally

Fixed Type Issue in Price

---

apps/mobile/app/(authenticated)/account/[id]/index.tsx
apps/mobile/components/SSBalanceChart.tsx

Hi, I updated balance history chart.
- Display UTXOs per transaction inside the chart.
- Navigate to UTXO detail page when tap the UTXO balance.
- Display transaction details on X-axis.
- Improved Zoom functionality.
- Display spent UTXOs with horizontal gradient.
- Improved label collision handling.

Updated Transaction Chart

---

apps/mobile/components/SSBalanceChart.tsx

Updated zoom user experience
Improved performance and optimized state management

Improve performance of balance chart

---

apps/mobile/app/(authenticated)/account/[id]/transaction/[txid]/index.tsx

- fix the amount
- color the amount

fix: wrong amount in tx details header

---

apps/mobile/app/(authenticated)/account/[id]/settings/labelExport.tsx
apps/mobile/app/(authenticated)/account/[id]/settings/labelImport.tsx
apps/mobile/utils/bip329.ts
apps/mobile/utils/filesystem.ts

Bip329 json lines

---

apps/mobile/app/(authenticated)/account/[id]/index.tsx
apps/mobile/app/(authenticated)/addMasterKey/index.tsx

Hide buttons for watch only

---

apps/mobile/app/(authenticated)/account/[id]/transaction/[txid]/utxo/[vout]/index.tsx
apps/mobile/locales/en.json

fix: utxo details i18n

---

apps/mobile/app/(authenticated)/addMasterKey/accountOptions.tsx
apps/mobile/app/(authenticated)/addMasterKey/watchOnlyOptions.tsx
apps/mobile/components/SSScriptVersionModal.tsx

refactor: script version modal

---

.github/workflows/ci.yml

Only run pipeline on non-draft PRs

fix: update workflow ci.yml

---

apps/mobile/constants/servers.ts

feat: add list of public bitcoin mainnet servers

---

apps/mobile/components/SSAccountCard.tsx
apps/mobile/hooks/useSyncAccountWithAddress.ts
apps/mobile/hooks/useSyncAccountWithWallet.ts
apps/mobile/store/accounts.ts
apps/mobile/types/models/Account.ts

Display that Accounts are Syncing

---

apps/mobile/app/(authenticated)/(stacks)/account/[id]/index.tsx
apps/mobile/app/(authenticated)/(stacks)/account/[id]/receive.tsx
apps/mobile/app/(authenticated)/(stacks)/account/[id]/transaction/[txid]/index.tsx
apps/mobile/app/(authenticated)/(stacks)/account/[id]/transaction/[txid]/utxo/[vout]/index.tsx
apps/mobile/components/SSAddressDisplay.tsx

Address chunks

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/accountList.tsx
apps/mobile/components/SSButton.tsx
apps/mobile/locales/en.json

Keep demo account block after key creation

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/index.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/receive.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/add/(common)/import/mnemonic/[keyIndex].tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/add/multiSig/finish.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/add/watchOnly/index.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/accountList.tsx
apps/mobile/app/(authenticated)/_layout.tsx
apps/mobile/components/SSNumberInput.tsx
apps/mobile/components/icons/SSIconSuccess.tsx
apps/mobile/hooks/useSyncAccountWithAddress.ts
apps/mobile/hooks/useSyncAccountWithWallet.ts

- Wrap around try catch and show error messages with sonner
- Fix isSyncing bug
- Fix invoice qr code generation
- Fix SSIconSuccess

Small fixes and improvements

---

apps/mobile/types/models/Utxo.ts
apps/mobile/utils/utxo.ts

Update type and document effectiveValue

Type update

---

apps/mobile/components/SSSankeyNodes.tsx
apps/mobile/hooks/useNodesAndLinks.ts
apps/mobile/locales/en.json

add missing label for inputs

---

apps/mobile/components/SSBubble.tsx

Previously it uses Roboto in Android. Now used the correct font.

Used SF Pro Text in SSBubble for Android

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/_layout.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/accountList.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/currency.tsx
apps/mobile/app/(authenticated)/(tabs)/_layout.tsx
apps/mobile/components/SSAccountCard.tsx
apps/mobile/components/SSDatePicker.tsx

In this pull request
✅ Fixed following Issues

Fixing issues on iOS

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/settings/index.tsx

In this pull request
✅ Fixed following Issue:

Fixing issues on iOS - 3

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/importOutputs.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/ioPreview.tsx
apps/mobile/locales/en.json
apps/mobile/utils/parse.ts

In this pull request
✅ Implementation:

Feature: Parse multiple outputs format

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/index.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/receive.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/ioPreview.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/previewMessage.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/signMessage.tsx
apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/walletSyncedConfirmation.tsx
apps/mobile/hooks/useGetAccountAddress.ts
apps/mobile/hooks/useGetAccountWallet.ts

Fix wallet not found

---

apps/mobile/app/(authenticated)/(tabs)/(signer,explorer,converter)/account/[id]/signAndSend/ioPreview.tsx
apps/mobile/components/SSCurrentTransactionChart.tsx
apps/mobile/components/SSMultipleSankeyDiagram.tsx

Fixed Sankey Gradient
